### ISSUE TITLE
Regression: semver-compatible updates marked with X

### ISSUE THREAD

**Issue by djc** [filllabs/dependi#109]
**Describe the bug**

For Rust dependencies I'm now seeing that available semver-compatible updates yield an upgradable decoration when only semver-compatible updates are available. This was not the case previously, and is undesirable at least for me (not sure if this is some new configuration).

**Screenshots**

<img width="906" alt="Screenshot 2024-08-19 at 14 26 00" src="https://github.com/user-attachments/assets/9c0b5fa2-9cfe-40e2-b4c7-7aecd309e35d">

I want to see only green checkboxes here, even if my `Cargo.lock` file is committed.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 0.7.8

**Comment by MOzanGul** [comment]
Hi @djc, this is because of the latest update regarding support of .lock files. You can disable that feature in the Extension settings.
Let us know if that works for you.

**Comment by djc** [comment]
It fills this immediate need but then causes problems with #51.

**Comment by serayuzgur** [comment]
Hi @djc ,
Does this solves you issue ?  Please test the attachment for test build. If works we will publish with new version.
[PR](https://github.com/filllabs/dependi/pull/113)

[vscode-extension.zip](https://github.com/user-attachments/files/16728404/vscode-extension.zip)

**Comment by djc** [comment]
Do you have guidance on how to install an extension from `.zip`?

**Comment by MOzanGul** [comment]
Firstly, unzip the folder.
Then you need to uninstall if there are installed versions of the extension.
After that, you can install the `.vsix` file following the instructions on the screenshot below.
![image](https://github.com/user-attachments/assets/771c8f5e-3fe2-4971-b0f0-ac554ef9c3f2)

**Comment by djc** [comment]
Honestly not sure i I can reliably reproduce this issue even with the marketplace version of the extension.

**Comment by MOzanGul** [comment]
Hi @djc ,
What do you suggest on how we we will go forward? We would like to know if you have any improvement ideas.

**Comment by masterflitzer** [comment]
what do you mean by semver-compatible updates (major/minor/patch)? i mean 0.7.2 is more up to date than 0.7.1 so the X is expected or am i missing something?

**Comment by djc** [comment]
In Cargo, 0.7.2 is semver-compatible with 0.7.1 and 1.10.3 is semver-compatible with 1.7.1. With Cargo, `cargo update` will let me painlessly update all semver-compatible updates, while I have to do manual work for upgrading across semver-incompatible boundaries (like 0.7 -> 0.8 or 1.13 -> 2.0).

**Comment by masterflitzer** [comment]
thanks for the explanation, i've always used crates/dependi as indication for when to update, not matter how the boundary is, the current behavior is pretty useful when you don't regularly run `cargo update`, i'd definitely like it if both ways would be supported e.g. through configuration (idc which is the default behavior)

**Comment by MOzanGul** [comment]
Hi @djc, after your comments we have discussed internally and would like to inform you about the how we will go forward.

> I would prefer not to see an X for crates that only have semver-compatible updates, only for crates that have semver-incompatible updates

- Our extension currently works this way. Since the versions used in Cargo.lock files are exact, we behave accordingly. In cases where the Cargo.lock file is present, we do not consider semver-compatible updates. As we focus on the actual version in use, we do not compare such updates and simply accept the version being used. This approach was implemented based on previous discussions.

> I would prefer not to see an alarm light for crates where the required version (in Cargo.toml) is vulnerable but the locked version (in Cargo.lock) is not vulnerable

- As long as the Cargo.lock file is present and the relevant setting is enabled, our application already defaults to using the locked value for processing and displays decorations accordingly. The current setup is designed to follow this behavior in all cases.
- This setting is enabled by default, so users do not need to take any extra steps. The setting can only be disabled if needed.

We will close this issue for now but feel free to reopen if you have any issues with how we go forward.
We appreciate your effort and contribution to Dependi.

**Comment by djc** [comment]
Sounds good, thanks for following up!
