### ISSUE TITLE
Support for pyproject.toml

### ISSUE THREAD

**Issue by mrijken** [filllabs/dependi#12]
**Is your feature request related to a problem? Please describe.**
I do not use requirement.txt for managing dependencies. I use Poetry with pyproject.toml

**Describe the solution you'd like**
Support for pyproject.toml

**Describe alternatives you've considered**
-

**Additional context**
Usage of requirements.txt is declining

**Comment by serayuzgur** [comment]
Seems like good idea @MOzanGul  we can plan it

**Comment by JP-Ellis** [comment]
I would like to expand on @mrijken's initial comment, as the Python ecosystem has 2 (and a bit) standards:

## The new standard: `pyproject.toml`

The `pyproject.toml` specification was created in [PEP 621](https://peps.python.org/pep-0621/#dependencies-optional-dependencies) and the most up to date specification is described [in the `packaging` docs](https://packaging.python.org/en/latest/specifications/pyproject-toml/#dependencies-optional-dependencies).

### The Poetry caveat

[Poetry](https://python-poetry.org/) uses `pyproject.toml`, but predates PEP 621, and therefore does _not_ confirm to it. Having said that, Poetry v2 will support the new standard. See [this roadmap ticket](https://github.com/python-poetry/roadmap/issues/3), and [this draft PR](https://github.com/python-poetry/poetry/pull/9135) implementing it. I don't know whether it is worth supporting Poetry's own standard, or encourage users to migrate the PEP 621 (and that would be a decision for Dependi).

## The older standard: `requirements.txt`

This is the historical standard, and is still frequently used especially when pinning dependencies to specific version (since there is no standard lockfile yet). A common pattern will be to have very broad specifications in the `pyproject.toml` (so broad as to sometimes not have any version requirements), and the pinning specific versions of all dependencies in a `requirements.txt` file.

The specification is described in [PEP 508](https://peps.python.org/pep-0508/)

**Comment by MOzanGul** [comment]
Hi, per your request we have added the support for pyproject.toml in our new 0.7.5 version. We hope you like using our extension with this file type.
We'd be really happy if you could review Dependi in VS Code Marketplace. Here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
@JP-Ellis @mrijken

**Comment by JP-Ellis** [comment]
Thanks, I can confirm it works! I did notice a couple of minor issues, though I will post that in separate issues 👍

**Comment by mrijken** [comment]
Thanks, It works great. I have added a review.
