### ISSUE TITLE
I want Dependi to show a mark when a library version is neither the latest nor too old.

### ISSUE THREAD

**Issue by CHRIBUR0309** [filllabs/dependi#13]
Now, when a library version is the latest, Dependi shows ✅️, right? And when it is too old, Dependi shows ❌️, right?

I think Dependi should show a mark, _e.g._ ❗️, when a library version is neither the latest nor too old.

**Comment by serayuzgur** [comment]
Hi @CHRIBUR0309  thanks for reaching. This is a discussion before actually. Most of the users wanted extension silent as possible. May be we can bind it to a setting , what do your think ?

**Comment by serayuzgur** [comment]
> Hi.
> 
> I can understand their opinions. How about giving Dependi a setting to configure how noisy it should be on VS Code?

We have inspected this. Please confirm that we understood the issue correctly:

Currently, we only warn users about MAJOR and MINOR version differences (`MAJOR.MINOR.PATCH`). We don't report PATCH differences since most package managers update PATCH versions automatically. What you requested is to also inform users about PATCH differences, correct?

**Comment by MOzanGul** [comment]
Hi @CHRIBUR0309, we have added a mark for reporting patch updates on our 0.7.5 version per your request.
We'd be really happy if you could review Dependi, here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
