### ISSUE TITLE
Parsing error for nested keys in Cargo.toml when specifying dependencies

### ISSUE THREAD

**Issue by cpud36** [filllabs/dependi#154]
**Describe the bug**
When specifying dependencies in `name.path = ...` format or `name.workspace = true` format the Dependi gives an error and stops parsing.

The crate compiles and runs just fine. (`cargo build && cargo run` do not return any errors). 

**To Reproduce**
1. Create a workspace with two dependencies (`depa`, and `depb`)
2. Edit `depa/Cargo.toml`: add `depb.path = "../depb"` to `[dependencies]` section.
4. See the error on `.` in `depb.path`

**Expected behavior**
No parse error on `depb.path`

**Screenshots**
![2024-09-26_10:13:24](https://github.com/user-attachments/assets/e7a6c73b-977a-4be0-8850-69f82415a207)

**Desktop (please complete the following information):**
 - OS: Linux
 - cargo: 1.80.0 (376290515 2024-07-16)

**Comment by ahmetasfour** [comment]
Hi @cpud36 
Thanks for your patience. We are testing the TOML format compliance, and if we detect any errors, we will make the necessary updates.

**Comment by MOzanGul** [comment]
Hi @cpud36, 
I want to ask a question regarding this issue and #155 . 

We have checked both issues and screenshots, we saw that the error messages are not in the format we use in Dependi. Since acknowledging this we think that this problem isn't about Dependi.

Do you use another extension that might be conflicting with Dependi? If so can you reply with it's name? 
Also please try disabling any extension that might conflict with Dependi and please check if the issue persists.

Thank you for your time and effort. Waiting for your reply.

**Comment by cpud36** [comment]
Hi @MOzanGul 

I have checked my extensions and I indeed have (deprecated) BetterTOML extension installed. Disabling it fixed the problem. 

The #155 still stays the same, though.

Thank you for your patience
