### ISSUE TITLE
Is this dep considered up to date? Or it should have a red cross?

### ISSUE THREAD

**Issue by DeveloperMatheus** [filllabs/dependi#202]
**Describe the bug**
Wrong icon for the dependency line

**To Reproduce**
1. Install the extension
2. Install the dep `i18next` on 24.0.2
3. Go to package.json

**Expected behavior**
The icon shown in the line of the dependency should be the red cross

**Screenshots**
![image](https://github.com/user-attachments/assets/d8df6b26-3829-4097-a642-0ec91bfbe31c)

**Desktop:**
 - OS: Windows 11

**Additional description**
When we hover the mouse over the dependency line, it shows a more up to date version, but i don't know why it has the green check

**Comment by MOzanGul** [comment]
Hi @DeveloperMatheus,
Since the last stable version of the `i18next` npm package is 24.0.5, we consider the version 24.0.2 as a green check. The reason behind that is, this is considered a PATCH update according semantic versioning.

Dependi only shows red cross icon on MAJOR and MINOR updates. 

Here is a link for semantic versioning documentation:
https://semver.org/

Feel free to ask if you have any other questions!
